version: "3.4"


volumes:
  volume-postgres:
services:

  db:

    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432


  cache:
    container_name: cache
    restart: always
    image: redis:5
    ports:
      - 6379:6379
    expose:
      - 6379

